### ISSUE TITLE
INSTALL

### ISSUE THREAD

**Issue by lidianxiang** [GSiSY/Sinsy-RRemix#1]
There is no file named INSTALL, i can't install this program in right way.

**Comment by GloomyGhost-MosquitoSeal** [comment]
thanks your report. I will fix it right now ------------------ 原始邮件 ------------------
发件人: "lidianxiang"<notifications@github.com>
发送时间: 2019年9月25日(星期三) 上午10:09
收件人: "GSiSY/Sinsy-RRemix"<Sinsy-RRemix@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [GSiSY/Sinsy-RRemix] INSTALL (#1)



There is no file named INSTALL, i can't install this program in right way.
 
&mdash;

**Comment by GloomyGhost-MosquitoSeal** [comment]
after `make`, use `make install `
